apiVersion: v2
name: myapp
description: Umbrella chart bundling the api and web subcharts
type: application
version: 0.2.1
dependencies:
  - name: myapp-api
    version: 0.0.0
    repository: oci://ghcr.io/goabonga/charts
  - name: myapp-web
    version: 0.0.2
    repository: oci://ghcr.io/goabonga/charts
